### ISSUE TITLE
Deployment link

### ISSUE THREAD

**Issue by danielwbeebe** [militsaneykova/unifinder#3]
I recommend:
(1) fixing a bug in the code in your views for when a university shows to make the URLs work. Right now, when a university is entered, the URL shows up in the browser, and the code for the link looks like this:
```
<a href>http://www.shu.edu/</a>

When the user clicks, this message shows up: {"message":"Not found!"}

That should look like this: 

<a href="http://www.shu.edu/"></a>
```

(2) adding your deployment link to the readme file: https://thawing-lake-70966.herokuapp.com/

**Comment by militsaneykova** [comment]
Thank you for your feedback, Dan ! Definitely helpful advice. I have to add the Readme file and to fix the  functionality, also the CSS.
